pip install pymssql

In [1]:
import pandas as pd
import pymssql

In [3]:
sql="""select * from TasksInSubcat831Denormalized"""

In [4]:
with pymssql.connect(server='hw-dev-sql-01' ,database='DEV_STANDART_D10Task_powerbi' ,charset = 'cp1251')as  conn:
                      
    
    cursor = conn.cursor()  
    df = pd.read_sql( sql,conn)

In [5]:
 df

,TaskID,CreatedTime,OwnerId,TaskText,ParentTaskId,EndTime,IsClosed,OrderedTime,PriorityId,StateId,...,ExtParam4718Value,ExtParam4745Value,ExtParam3217Value,ExtParam3217NativeValue,ExtParam6256Value,ExtParam6256NativeValue,ExtParam6257Value,ExtParam6257NativeValue,LocalizedTaskTextId,ExtParam6386Value
0,1466688,2018-04-03 08:01:38.440,3,"ВИВА, Академия красоты (Москва, Ленинградский ...",NaN,2018-12-23 17:16:44.457,True,NaT,1,11,...,,1,,NaN,,NaT,,NaT,None,None
1,1466689,2018-04-03 08:05:07.993,3,"Научный центр рентгенорадиологии (Москва, Проф...",NaN,2019-01-15 17:44:26.603,True,NaT,1,11,...,,106,,NaN,,NaT,,NaT,None,None
2,1466690,2018-04-03 08:06:13.290,3,"Лечебно-диагностический центр №12, МО РФ (Моск...",NaN,2019-10-07 08:01:16.987,True,NaT,1,11,...,,1388,,NaN,,NaT,,NaT,None,None
3,1466692,2018-04-03 08:08:09.370,3,"Поликлиника РАО Газпром (Москва, Наметкина ул....",NaN,NaT,False,NaT,1,17,...,,14,0,0.0,,NaT,,NaT,None,None
4,1466693,2018-04-03 08:08:09.590,3,Центральный научно-исследовательский институт ...,NaN,NaT,False,NaT,1,17,...,,19,,NaN,,NaT,,NaT,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46983,5151466,2021-09-21 21:48:24.047,3,"Иломед (Москва, Земляной Вал 34, стр.1)",NaN,NaT,False,NaT,1,1,...,,717,,NaN,,NaT,,NaT,None,
46984,5151475,2021-09-21 21:51:40.547,3,"ВП ОАО РЖД (Москва, Новая Басманная ул., 5)",NaN,NaT,False,NaT,1,1,...,,19863,,NaN,,NaT,,NaT,None,
46985,5151497,2021-09-21 22:04:17.343,3,"Городская клиническая больница №7 (Москва, Кол...",NaN,NaT,False,NaT,1,1,...,Миронов Игорь Алексеевич,61717,,NaN,,NaT,,NaT,None,
46986,5151521,2021-09-21 22:33:49.460,3,Российская детская клиническая больница (Москв...,NaN,NaT,False,NaT,1,1,...,,61453,,NaN,,NaT,,NaT,None,
46987,5151523,2021-09-21 22:58:29.127,3,Российская детская клиническая больница (Москв...,NaN,NaT,False,NaT,1,1,...,,61454,,NaN,,NaT,,NaT,None,

In [8]:
df = pd.read_sql( sql,conn)

DatabaseError: Execution failed on sql: select * from TasksInSubcat831Denormalized
Connection is closed.
unable to rollback

In [22]:
df.head(10)

,TaskID,CreatedTime,OwnerId,TaskText,ParentTaskId,EndTime,IsClosed,OrderedTime,PriorityId,StateId,...,ExtParam4718Value,ExtParam4745Value,ExtParam3217Value,ExtParam3217NativeValue,ExtParam6256Value,ExtParam6256NativeValue,ExtParam6257Value,ExtParam6257NativeValue,LocalizedTaskTextId,ExtParam6386Value
0,1466688,2018-04-03 08:01:38.440,3,"ВИВА, Академия красоты (Москва, Ленинградский ...",NaN,2018-12-23 17:16:44.457,True,NaT,1,11,...,,1,,NaN,,NaT,,NaT,None,None
1,1466689,2018-04-03 08:05:07.993,3,"Научный центр рентгенорадиологии (Москва, Проф...",NaN,2019-01-15 17:44:26.603,True,NaT,1,11,...,,106,,NaN,,NaT,,NaT,None,None
2,1466690,2018-04-03 08:06:13.290,3,"Лечебно-диагностический центр №12, МО РФ (Моск...",NaN,2019-10-07 08:01:16.987,True,NaT,1,11,...,,1388,,NaN,,NaT,,NaT,None,None
3,1466692,2018-04-03 08:08:09.370,3,"Поликлиника РАО Газпром (Москва, Наметкина ул....",NaN,NaT,False,NaT,1,17,...,,14,0,0.0,,NaT,,NaT,None,None
4,1466693,2018-04-03 08:08:09.590,3,Центральный научно-исследовательский институт ...,NaN,NaT,False,NaT,1,17,...,,19,,NaN,,NaT,,NaT,None,None
5,1466694,2018-04-03 08:08:09.760,3,"Семейный доктор №2, Клиника (Москва, Генерала ...",NaN,2018-12-14 13:38:59.030,True,NaT,1,11,...,,28836,,NaN,,NaT,,NaT,None,None
6,1466695,2018-04-03 08:08:09.917,3,"Городская клиническая больница №67 (Москва, Са...",NaN,2019-01-15 21:05:19.673,True,NaT,1,11,...,,19754,,NaN,,NaT,,NaT,None,None
7,1466696,2018-04-03 08:08:10.073,3,"Лечебно-диагностический центр №12, МО РФ (Моск...",NaN,NaT,False,NaT,1,17,...,,1393,,NaN,,NaT,,NaT,None,None
8,1466697,2018-04-03 08:08:10.243,3,"Городская клиническая больница №13 (Москва, Ве...",NaN,2019-12-09 08:01:08.170,True,NaT,1,11,...,"Чирков Павел Александрович, Штефанова Алла Юрь...",26,,NaN,,NaT,,NaT,None,None
9,1466698,2018-04-03 08:08:10.417,3,"Артрологический центр, МЦ (Москва, Крутицкий 4...",NaN,2019-01-15 17:44:26.837,True,NaT,1,11,...,,,,NaN,,NaT,,NaT,None,None

In [23]:
df

,TaskID,CreatedTime,OwnerId,TaskText,ParentTaskId,EndTime,IsClosed,OrderedTime,PriorityId,StateId,...,ExtParam4718Value,ExtParam4745Value,ExtParam3217Value,ExtParam3217NativeValue,ExtParam6256Value,ExtParam6256NativeValue,ExtParam6257Value,ExtParam6257NativeValue,LocalizedTaskTextId,ExtParam6386Value
0,1466688,2018-04-03 08:01:38.440,3,"ВИВА, Академия красоты (Москва, Ленинградский ...",NaN,2018-12-23 17:16:44.457,True,NaT,1,11,...,,1,,NaN,,NaT,,NaT,None,None
1,1466689,2018-04-03 08:05:07.993,3,"Научный центр рентгенорадиологии (Москва, Проф...",NaN,2019-01-15 17:44:26.603,True,NaT,1,11,...,,106,,NaN,,NaT,,NaT,None,None
2,1466690,2018-04-03 08:06:13.290,3,"Лечебно-диагностический центр №12, МО РФ (Моск...",NaN,2019-10-07 08:01:16.987,True,NaT,1,11,...,,1388,,NaN,,NaT,,NaT,None,None
3,1466692,2018-04-03 08:08:09.370,3,"Поликлиника РАО Газпром (Москва, Наметкина ул....",NaN,NaT,False,NaT,1,17,...,,14,0,0.0,,NaT,,NaT,None,None
4,1466693,2018-04-03 08:08:09.590,3,Центральный научно-исследовательский институт ...,NaN,NaT,False,NaT,1,17,...,,19,,NaN,,NaT,,NaT,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46923,5145124,2021-09-20 00:07:53.630,3,МЦ Первый доктор (Cеверный б-р д 7 Б),NaN,NaT,False,NaT,1,1,...,,60127,,NaN,,NaT,,NaT,None,
46924,5145125,2021-09-20 00:09:18.577,3,"ВП УПД РФ (Москва, Плющиха ул., 14)",1472578.0,NaT,False,NaT,1,1,...,,2020,,NaN,,NaT,,NaT,None,
46925,5145155,2021-09-20 00:48:18.263,3,"17 Роддом, филиал ГБУЗ ГКБ им. В. В. Вересаева...",NaN,NaT,False,NaT,1,1,...,,40870,,NaN,,NaT,,NaT,None,
46926,5145163,2021-09-20 00:50:02.350,3,ГБУЗ ГП № 6 ДЗМ Филиал № 4 (ГП № 164) (г. Моск...,NaN,NaT,False,NaT,1,1,...,,25414,,NaN,,NaT,,NaT,None,
46927,5145167,2021-09-20 00:51:16.227,3,ГБУЗ ГП № 6 ДЗМ Филиал № 4 (ГП № 164) (г. Моск...,NaN,NaT,False,NaT,1,1,...,,1025,,NaN,,NaT,,NaT,None,

In [7]:
conn.close()